name: AfyShell
version: '${project.version}'
main: net.afyer.afyshell.AfyShell
author: Nipuru
api-version: 1.17
depend: [ AfyLib ]
commands:
  afyshell:
    aliases:
      - sh
      - ash
      - shell
    description: AfyShell Base Command